[package]
name = "lainos"
version = "0.1.0"

[lib]
crate-type = ["staticlib"]
path = "src/kmain.rs"

[profile.dev]
panic = "abort"
lto = true
debug = true
opt-level = 1

[profile.test]
panic = "abort"
lto = true
debug = true

[profile.release]
panic = "abort"
lto = true
#opt-level = 1
opt-level = 2

[dependencies]
spin = "*"
#pi = { path = "../pi", features = ["std"] }

stack-vec = { path = "stack-vec" }
