[dependencies]
core = {}
#std_unicode = {}

[dependencies.compiler_builtins]
features = ["mem"]
stage = 1

#[dependencies.std]
#path = "../std"
#stage = 2

[target.raspi3-lainos.dependencies]
alloc = {}
