#[repr(u8)]
pub enum Packet {
    HALT = 0,
    NOP = 1,

    FLUSH = 4,
    FLUSH_ALL = 5,
    START_TILE_BINNING = 6,
    INCREMENT_SEMAPHORE = 7,
    WAIT_ON_SEMAPHORE = 8,

    BRANCH = 16,
    BRANCH_TO_SUB_LIST = 17,
    RETURN_FROM_SUBLIST = 18,

    STORE_MS_TILE_BUFFER = 24,
    STORE_MS_TILE_BUFFER_AND_EOF = 25,
    STORE_FULL_RES_TILE_BUFFER = 26,
    LOAD_FULL_RES_TILE_BUFFER = 27,
    STORE_TILE_BUFFER_GENERAL = 28,
    LOAD_TILE_BUFFER_GENERAL = 29,

    GL_INDEXED_PRIMITIVE = 32,
    GL_ARRAY_PRIMITIVE = 33,
    VG_COORDINATE_ARRAY_PRIMITIVES = 41,

    COMPRESSED_PRIMITIVE = 48,
    CLIPPED_COMPRESSED_PRIMITIVE = 49,

    PRIMITIVE_LIST_FORMAT = 56,

    GL_SHADER_STATE = 64,
    NV_SHADER_STATE = 65,
    VG_SHADER_STATE = 66,
    VG_INLINE_SHADER_RECORD = 67,

    CONFIGURATION_BITS = 96,
    FLAT_SHADE_FLAGS = 97,
    POINT_SIZE = 98,
    LINE_WIDTH = 99,
    RHT_X_BOUNDARY = 100,
    DEPTH_OFFSET = 101,
    CLIP_WINDOW = 102,
    VIEWPORT_OFFSET = 103,
    Z_CLIPPING = 104,
    CLIPPER_XY_SCALING = 105,
    CLIPPER_Z_SCALING = 106,

    TILE_BINNING_MODE_CONFIG = 112,
    TILE_RENDERING_MODE_CONFIG = 113,
    CLEAR_COLORS = 114,
    TILE_COORDINATES = 115,

    // Not an actual hardware packet -- this is what we use to put
    // references to GEM bos in the command stream, since we need the u32
    // int the actual address packet in order to store the offset from the
    // start of the BO.
    //VC4_PACKET_GEM_HANDLES = 254,
}
