[dependencies]
std_unicode = {}

[dependencies.core]
stage = 0

[dependencies.alloc]
stage = 1

#[dependencies.compiler_builtins]
#features = ["mem"]
#stage = 1

#[dependencies.std]
#path = "../std"
#stage = 2
